### ISSUE TITLE
Undefined array key

### ISSUE THREAD

**Issue by elbandi** [henzeb/laravel-console-facade#1]
I use this package for a laravel-zero app.
If i run app with any arguments, it works good: `php my-app list`

    MyApp  unreleased
    
    USAGE: my-app <command> [options] [arguments]
    
    completion       Dump the shell completion script
    migrate          Run the database migrations

But if i run without any argument (eg: get the version): `php my-app --version`
I got this error:

    In ConsoleServiceProvider.php line 114:
    
      Undefined array key ""

**Comment by henzeb** [comment]
Solved this issue, that only happened in Laravel Zero 9
